# Generated by Django 4.2.1 on 2023-06-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_comment_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='interests',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='picture',
            field=models.FileField(default='', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='skills',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='surname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
