# Generated by Django 4.2.1 on 2023-06-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_bloguser_interests_bloguser_picture_bloguser_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='profession',
            field=models.CharField(default='', max_length=50),
        ),
    ]
